# Generated by Django 5.2.7 on 2026-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('data_nascimento', models.DateField()),
                ('controle_acesso', models.CharField(choices=[('admin', 'Admin'), ('coordenador', 'Coordenador'), ('protocolo', 'Protocolo'), ('professor', 'Professor')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cadastr_perfil',
            },
        ),
    ]
