# Generated by Django 5.2.7 on 2026-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviso",
            name="visualizacao",
            field=models.CharField(choices=[("admin", "Admin"), ("coordenador", "Coordenador"), ("protocolo", "Protocolo"), ("professor", "Professor")], max_length=20),
        ),
    ]
