# Generated by Django 5.2.7 on 2026-03-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_aviso_visualizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuadroAviso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("link", models.URLField(blank=True)),
                ("data_fim_publicacao", models.DateField()),
                ("imagem_capa", models.ImageField(blank=True, null=True, upload_to="quadro_avisos/")),
                ("imagem_1", models.ImageField(blank=True, null=True, upload_to="quadro_avisos/")),
                ("documento", models.FileField(blank=True, null=True, upload_to="quadro_avisos/")),
                ("visualizacao", models.CharField(choices=[("admin", "Admin"), ("coordenador", "Coordenador"), ("protocolo", "Protocolo"), ("professor", "Professor")], max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
