# Generated by Django 5.2.7 on 2026-03-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_quadro_aviso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_comunicado", models.CharField(max_length=40)),
                ("data_emissao", models.DateField()),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("link", models.URLField(blank=True)),
                ("imagem_capa", models.ImageField(blank=True, null=True, upload_to="comunicados/")),
                ("documento_1", models.FileField(blank=True, null=True, upload_to="comunicados/")),
                ("documento_2", models.FileField(blank=True, null=True, upload_to="comunicados/")),
                ("visualizacao", models.CharField(choices=[("admin", "Admin"), ("coordenador", "Coordenador"), ("protocolo", "Protocolo"), ("professor", "Professor")], max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
