# Generated by Django 5.2.7 on 2026-03-17 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_create_comunicado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicado",
            name="data_emissao",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
