# Generated by Django 5.2.7 on 2026-03-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_comunicado_data_emissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviso",
            name="visualizacao",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="quadroaviso",
            name="visualizacao",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="comunicado",
            name="visualizacao",
            field=models.JSONField(default=list),
        ),
    ]
