# Generated by Django 5.2.7 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_visualizacao_multi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_evento", models.DateField()),
                ("horario_evento", models.TimeField()),
                ("evento", models.CharField(max_length=200)),
                ("local", models.CharField(max_length=200)),
                ("imagem_capa", models.ImageField(blank=True, null=True, upload_to="eventos/")),
                ("imagem_1", models.ImageField(blank=True, null=True, upload_to="eventos/")),
                ("documento", models.FileField(blank=True, null=True, upload_to="eventos/")),
                ("descricao", models.TextField()),
                ("visualizacao", models.JSONField(default=list)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

