# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_aviso_quadroenvio_status_lido_em"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="data_evento",
            new_name="data_inicio",
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="horario_evento",
            new_name="horario_inicio",
        ),
        migrations.AddField(
            model_name="evento",
            name="data_final",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="horario_final",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
