# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def migrar_imagens_evento(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")
    EventoImagem = apps.get_model("core", "EventoImagem")

    for evento in Evento.objects.all():
        if evento.imagem_1:
            EventoImagem.objects.create(evento=evento, imagem=evento.imagem_1.name)


def desfazer_migracao_imagens_evento(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")
    EventoImagem = apps.get_model("core", "EventoImagem")

    for evento in Evento.objects.all():
        imagens = list(EventoImagem.objects.filter(evento=evento).order_by("id")[:1])
        for imagem in imagens:
            evento.imagem_1 = imagem.imagem.name
        if imagens:
            evento.save(update_fields=["imagem_1"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_update_evento_datas_imagens"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoImagem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagem", models.ImageField(upload_to="eventos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.evento",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrar_imagens_evento, desfazer_migracao_imagens_evento),
        migrations.RemoveField(
            model_name="evento",
            name="imagem_1",
        ),
    ]
