# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def migrar_imagens(apps, schema_editor):
    Aviso = apps.get_model("core", "Aviso")
    AvisoImagem = apps.get_model("core", "AvisoImagem")
    QuadroAviso = apps.get_model("core", "QuadroAviso")
    QuadroAvisoImagem = apps.get_model("core", "QuadroAvisoImagem")

    for aviso in Aviso.objects.all():
        if aviso.imagem_1:
            AvisoImagem.objects.create(aviso=aviso, imagem=aviso.imagem_1.name)

    for aviso in QuadroAviso.objects.all():
        if aviso.imagem_1:
            QuadroAvisoImagem.objects.create(quadro_aviso=aviso, imagem=aviso.imagem_1.name)


def desfazer_migracao_imagens(apps, schema_editor):
    Aviso = apps.get_model("core", "Aviso")
    AvisoImagem = apps.get_model("core", "AvisoImagem")
    QuadroAviso = apps.get_model("core", "QuadroAviso")
    QuadroAvisoImagem = apps.get_model("core", "QuadroAvisoImagem")

    for aviso in Aviso.objects.all():
        imagens = list(AvisoImagem.objects.filter(aviso=aviso).order_by("id")[:1])
        for imagem in imagens:
            aviso.imagem_1 = imagem.imagem.name
        if imagens:
            aviso.save(update_fields=["imagem_1"])

    for aviso in QuadroAviso.objects.all():
        imagens = list(QuadroAvisoImagem.objects.filter(quadro_aviso=aviso).order_by("id")[:1])
        for imagem in imagens:
            aviso.imagem_1 = imagem.imagem.name
        if imagens:
            aviso.save(update_fields=["imagem_1"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_evento_imagens_dinamicas"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoImagem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagem", models.ImageField(upload_to="avisos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.aviso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuadroAvisoImagem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagem", models.ImageField(upload_to="quadro_avisos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "quadro_aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.quadroaviso",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrar_imagens, desfazer_migracao_imagens),
        migrations.RemoveField(
            model_name="aviso",
            name="imagem_1",
        ),
        migrations.RemoveField(
            model_name="quadroaviso",
            name="imagem_1",
        ),
    ]
