# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def migrar_documentos(apps, schema_editor):
    Aviso = apps.get_model("core", "Aviso")
    AvisoDocumento = apps.get_model("core", "AvisoDocumento")
    QuadroAviso = apps.get_model("core", "QuadroAviso")
    QuadroAvisoDocumento = apps.get_model("core", "QuadroAvisoDocumento")
    Comunicado = apps.get_model("core", "Comunicado")
    ComunicadoDocumento = apps.get_model("core", "ComunicadoDocumento")
    Evento = apps.get_model("core", "Evento")
    EventoDocumento = apps.get_model("core", "EventoDocumento")

    for aviso in Aviso.objects.all():
        if aviso.documento:
            AvisoDocumento.objects.create(aviso=aviso, documento=aviso.documento.name)

    for aviso in QuadroAviso.objects.all():
        if aviso.documento:
            QuadroAvisoDocumento.objects.create(quadro_aviso=aviso, documento=aviso.documento.name)

    for comunicado in Comunicado.objects.all():
        if comunicado.documento_1:
            ComunicadoDocumento.objects.create(comunicado=comunicado, documento=comunicado.documento_1.name)
        if comunicado.documento_2:
            ComunicadoDocumento.objects.create(comunicado=comunicado, documento=comunicado.documento_2.name)

    for evento in Evento.objects.all():
        if evento.documento:
            EventoDocumento.objects.create(evento=evento, documento=evento.documento.name)


def desfazer_migracao_documentos(apps, schema_editor):
    Aviso = apps.get_model("core", "Aviso")
    AvisoDocumento = apps.get_model("core", "AvisoDocumento")
    QuadroAviso = apps.get_model("core", "QuadroAviso")
    QuadroAvisoDocumento = apps.get_model("core", "QuadroAvisoDocumento")
    Comunicado = apps.get_model("core", "Comunicado")
    ComunicadoDocumento = apps.get_model("core", "ComunicadoDocumento")
    Evento = apps.get_model("core", "Evento")
    EventoDocumento = apps.get_model("core", "EventoDocumento")

    for aviso in Aviso.objects.all():
        documentos = list(AvisoDocumento.objects.filter(aviso=aviso).order_by("id")[:1])
        for documento in documentos:
            aviso.documento = documento.documento.name
        if documentos:
            aviso.save(update_fields=["documento"])

    for aviso in QuadroAviso.objects.all():
        documentos = list(QuadroAvisoDocumento.objects.filter(quadro_aviso=aviso).order_by("id")[:1])
        for documento in documentos:
            aviso.documento = documento.documento.name
        if documentos:
            aviso.save(update_fields=["documento"])

    for comunicado in Comunicado.objects.all():
        documentos = list(ComunicadoDocumento.objects.filter(comunicado=comunicado).order_by("id")[:2])
        for index, documento in enumerate(documentos, start=1):
            setattr(comunicado, f"documento_{index}", documento.documento.name)
        if documentos:
            comunicado.save(update_fields=[f"documento_{index}" for index in range(1, len(documentos) + 1)])

    for evento in Evento.objects.all():
        documentos = list(EventoDocumento.objects.filter(evento=evento).order_by("id")[:1])
        for documento in documentos:
            evento.documento = documento.documento.name
        if documentos:
            evento.save(update_fields=["documento"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_avisos_imagens_dinamicas"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoDocumento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("documento", models.FileField(upload_to="avisos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.aviso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuadroAvisoDocumento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("documento", models.FileField(upload_to="quadro_avisos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "quadro_aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.quadroaviso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComunicadoDocumento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("documento", models.FileField(upload_to="comunicados/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "comunicado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.comunicado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoDocumento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("documento", models.FileField(upload_to="eventos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.evento",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrar_documentos, desfazer_migracao_documentos),
        migrations.RemoveField(
            model_name="aviso",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="quadroaviso",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="comunicado",
            name="documento_1",
        ),
        migrations.RemoveField(
            model_name="comunicado",
            name="documento_2",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="documento",
        ),
    ]
