from django.urls import path

from . import views

urlpatterns = [
    path("", views.login, name="login"),
    path("login/", views.login, name="login"),
    path("home/", views.home, name="home"),
    path("fotos/", views.lista_fotos, name="lista_fotos"),
    path("fotos/<int:pk>/", views.detalhe_fotos, name="detalhe_fotos"),
    path("fotos/<int:pk>/editar/", views.editar_fotos, name="editar_fotos"),
    path("fotos/<int:pk>/excluir/", views.excluir_fotos, name="excluir_fotos"),
    path("fotos/cadastro/", views.cadastro_fotos, name="cadastro_fotos"),
    path("videos/", views.lista_videos, name="lista_videos"),
    path("videos/<int:pk>/", views.detalhe_videos, name="detalhe_videos"),
    path("videos/<int:pk>/editar/", views.editar_videos, name="editar_videos"),
    path("videos/<int:pk>/excluir/", views.excluir_videos, name="excluir_videos"),
    path("videos/cadastro/", views.cadastro_videos, name="cadastro_videos"),
    path("aniversariantes/", views.aniversariantes, name="aniversariantes"),
    path("avisos/", views.lista_avisos, name="lista_avisos"),
    path("avisos/envios/", views.avisos_envios_pendentes, name="avisos_envios_pendentes"),
    path("avisos/leituras/", views.avisos_leituras, name="avisos_leituras"),
    path("avisos/envios/<int:envio_id>/enviar/", views.aviso_enviar_whatsapp, name="aviso_enviar_whatsapp"),
    path("avisos/<int:pk>/", views.detalhe_aviso, name="detalhe_aviso"),
    path("avisos/<int:pk>/confirmar-leitura/", views.aviso_confirmar_leitura, name="aviso_confirmar_leitura"),
    path("avisos/<int:pk>/editar/", views.editar_aviso, name="editar_aviso"),
    path("avisos/<int:pk>/excluir/", views.excluir_aviso, name="excluir_aviso"),
    path("avisos/cadastro/", views.cadastro_avisos, name="cadastro_avisos"),
    path("quadro-avisos/", views.lista_quadro_avisos, name="lista_quadro_avisos"),
    path("quadro-avisos/envios/", views.quadro_avisos_envios_pendentes, name="quadro_avisos_envios_pendentes"),
    path("quadro-avisos/leituras/", views.quadro_avisos_leituras, name="quadro_avisos_leituras"),
    path(
        "quadro-avisos/envios/<int:envio_id>/enviar/",
        views.quadro_aviso_enviar_whatsapp,
        name="quadro_aviso_enviar_whatsapp",
    ),
    path("quadro-avisos/<int:pk>/", views.detalhe_quadro_aviso, name="detalhe_quadro_aviso"),
    path(
        "quadro-avisos/<int:pk>/confirmar-leitura/",
        views.quadro_aviso_confirmar_leitura,
        name="quadro_aviso_confirmar_leitura",
    ),
    path("quadro-avisos/<int:pk>/editar/", views.editar_quadro_aviso, name="editar_quadro_aviso"),
    path("quadro-avisos/<int:pk>/excluir/", views.excluir_quadro_aviso, name="excluir_quadro_aviso"),
    path("quadro-avisos/cadastro/", views.cadastro_quadro_avisos, name="cadastro_quadro_avisos"),
    path("comunicados/", views.lista_comunicados, name="lista_comunicados"),
    path("comunicados/envios/", views.comunicados_envios_pendentes, name="comunicados_envios_pendentes"),
    path("comunicados/leituras/", views.comunicados_leituras, name="comunicados_leituras"),
    path(
        "comunicados/envios/<int:envio_id>/enviar/",
        views.comunicado_enviar_whatsapp,
        name="comunicado_enviar_whatsapp",
    ),
    path("comunicados/<int:pk>/", views.detalhe_comunicado, name="detalhe_comunicado"),
    path(
        "comunicados/<int:pk>/confirmar-leitura/",
        views.comunicado_confirmar_leitura,
        name="comunicado_confirmar_leitura",
    ),
    path("comunicados/<int:pk>/editar/", views.editar_comunicado, name="editar_comunicado"),
    path("comunicados/<int:pk>/excluir/", views.excluir_comunicado, name="excluir_comunicado"),
    path("comunicados/cadastro/", views.cadastro_comunicados, name="cadastro_comunicados"),
    path("eventos/", views.lista_eventos, name="lista_eventos"),
    path("eventos/envios/", views.eventos_envios_pendentes, name="eventos_envios_pendentes"),
    path(
        "eventos/envios/<int:envio_id>/enviar/",
        views.evento_enviar_whatsapp,
        name="evento_enviar_whatsapp",
    ),
    path("eventos/<int:pk>/", views.detalhe_evento, name="detalhe_evento"),
    path("eventos/<int:pk>/editar/", views.editar_evento, name="editar_evento"),
    path("eventos/<int:pk>/excluir/", views.excluir_evento, name="excluir_evento"),
    path("eventos/cadastro/", views.cadastro_eventos, name="cadastro_eventos"),
]
